### PR TITLE
AOSP 7.1.2 HAL3

### PR DESCRIPTION
**Pull request by MZO9400**
(1/3) This set of commits is to get HAL3 working on OnePlus2 without Nougat blobs

@smeroni68 @B--B can you please test other devices and see if it is fine to merge the PR

### CODE REVIEW

**Comment by MZO9400** [comment]
https://github.com/AOSP-JF-MM/platform_device_qcom_sepolicy/pull/2
&
https://github.com/AOSP-JF-MM/platform_system_sepolicy/pull/1

Go along with this change.

**Comment by smeroni68** [comment]
Need BB to merge for a test.

**Comment by B--B** [comment]
@MZO9400 no problem for me, i will take a look at sepolicy later but it's not a problem as we are running selinux in permissive mode. Feel free to merge the patches in main branches :)

**Comment by MZO9400** [comment]
Okay! Thank you

**Pull request merged**
